### PR TITLE
fix multiple dbt.config.get in python model

### LINKED ISSUE #5846: [CT-1189] [Bug] Missing configs when multiple dbt.config.get in Python model
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Not all configs show up in generated code (`config_dict`) for Python model with multiple `dbt.config.get()` calls

### Expected Behavior

All configs are included in `config_dict`

### Steps To Reproduce

Define a model like:
```python
def model(dbt, session):

    PROJECT_ID = dbt.config.get("POSTHOG_PROJECT_ID")
    POSTHOG_TOKEN = dbt.config.get("POSTHOG_TOKEN")

    df = dbt.ref("orders")

    return df
```
With configs like:
```yml
version: 2
models:
  - name: something
    config:
      PROJECT_ID: something
      POSTHOG_TOKEN: something_else
```

Run `dbt compile`. See compiled output like:
```
def model(dbt, session):

    PROJECT_ID = dbt.config.get("POSTHOG_PROJECT_ID")
    POSTHOG_TOKEN = dbt.config.get("POSTHOG_TOKEN")

    df = dbt.ref("orders")

    return df


# This part is user provided model code
# you will need to copy the next section to run the code
# COMMAND ----------
# this part is dbt logic for get ref work, do not modify

def ref(*args,dbt_load_df_function):
    refs = {"orders": "ad_hoc.dbt_jcohen.orders"}
    key = ".".join(args)
    return dbt_load_df_function(refs[key])


def source(*args, dbt_load_df_function):
    sources = {}
    key = ".".join(args)
    return dbt_load_df_function(sources[key])


config_dict = {'POSTHOG_TOKEN': 'something_else'}


class config:
    def __init__(self, *args, **kwargs):
        pass

    @staticmethod
    def get(key):
        return config_dict.get(key)

class this:
    """dbt.this() or dbt.this.identifier"""
    database = 'ad_hoc'
    schema = 'dbt_jcohen'
    identifier = 'something'
    def __repr__(self):
        return 'ad_hoc.dbt_jcohen.something'


class dbtObj:
    def __init__(self, load_df_function) -> None:
        self.source = lambda *args: source(*args, dbt_load_df_function=load_df_function)
        self.ref = lambda *args: ref(*args, dbt_load_df_function=load_df_function)
        self.config = config
        self.this = this()
        self.is_incremental = False

# COMMAND ----------

# To run this in snowsight, you need to select entry point to be main
# And you may have to modify the return type to text to get the result back
# def main(session):
#     dbt = dbtObj(session.table)
#     df = model(dbt, session)
#     return df.collect()

# to run this in local notebook, you need to create a session following examples https://github.com/Snowflake-Labs/sfguide-getting-started-snowpark-python
# then you can do the following to run model
# dbt = dbtObj(session.table)
# df = model(dbt, session)
```

Namely:
```
config_dict = {'POSTHOG_TOKEN': 'something_else'}
```

### Relevant log output

_No response_

### Environment

```markdown
- OS:
- Python:
- dbt: 1.3.0-b2 (I think latest `main`)
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ChenyuLInx**
resolves #5846

### Description
Fix for config missing when multiple are specified

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

File: core/dbt/include/global_project/macros/python_model/python.sql [hunk 1]
```diff
@@ -56,8 +56,8 @@ class config:
         pass
 
     @staticmethod
-    def get(key):
-        return config_dict.get(key)
+    def get(key, default=None):
+        return config_dict.get(key, default=None)
```
Comment (stu-k) [inline core/dbt/include/global_project/macros/python_model/python.sql:60]: This python looks slightly off, can you do `default=None` in a method invocation? I would think this should be
```suggestion
    def get(key, default=None):
        return config_dict.get(key, default)
```
since `default` already defaults to `None`.

File: core/dbt/parser/models.py [hunk 2]
```diff
@@ -205,16 +205,16 @@ def parse_python_model(self, node, config, context):
 
         dbtParser = PythonParseVisitor(node)
         dbtParser.visit(tree)
-
+        config_get_keys = []
```
Comment (stu-k) [inline core/dbt/parser/models.py:208]: Not a blocker, but `config_get_keys` is hard to reason about for me. `config_keys_used` is a little easier to understand, if that is what this is meant to hold.

Comment (ChenyuLInx) [reply core/dbt/parser/models.py]: Thanks!! It's def easier to understand! Updated

**Review by stu-k — APPROVED** [review]
Comments addressed, nothing else stands out 👍
